[program:smkmuhbligo-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/smkmuhbligo/artisan queue:work redis --queue=ai,default --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/smkmuhbligo/storage/logs/worker.log
stopwaitsecs=3600
